# Generated by Django 5.2.4 on 2025-07-13 12:25

import django.db.models.deletion
import ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ticketing.models.ticket_image_upload_path, verbose_name='تصویر')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticketing.ticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر تیکت',
                'verbose_name_plural': 'تصاویر تیکت',
            },
        ),
    ]
